version: 2

builds:
  - main: ./cmd/chp
    binary: chp
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "chp_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - repository:
      owner: lollipopai
      name: homebrew-tap
    homepage: https://github.com/lollipopai/cli
    description: Cherrypick CLI - interact with the Cherrypick API
    license: MIT
    install: |
      bin.install "chp"
